 CREATE DATABASE nodelogin;

 USE nodelogin;

 CREATE TABLE IF NOT EXISTS Usuarios (
 	ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 	Cedula, VARCHAR(10) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Correo VARCHAR(100) NOT NULL,
 	Clave VARCHAR(255) NOT NULL,
 	Rol VARCHAR(50) NOT NULL
 );